DEVICE_DESCRIPTION = "STMicroelectronics Virtual COM Port"
BAUDRATE = 8_000_000
SERIAL_TIMEOUT_SECONDS = 0.05

MATRIX_ROWS = 32
MATRIX_COLUMNS = 128
PAYLOAD_SIZE = MATRIX_ROWS * MATRIX_COLUMNS * 2

HEADER_MAGIC = b"\xAA\x55"
SOURCE_ID_SIZE = 1
CRC_SIZE = 4
TAIL_MAGIC = b"\x55\xAA"

SOURCE_ID_OFFSET = len(HEADER_MAGIC)
PAYLOAD_OFFSET = SOURCE_ID_OFFSET + SOURCE_ID_SIZE
CRC_OFFSET = PAYLOAD_OFFSET + PAYLOAD_SIZE
TAIL_OFFSET = CRC_OFFSET + CRC_SIZE
FRAME_SIZE = TAIL_OFFSET + len(TAIL_MAGIC)

GUI_REFRESH_INTERVAL_MS = 33
